# Generated by Django 3.1.2 on 2020-10-15 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_name', models.CharField(max_length=50)),
                ('about', models.CharField(max_length=50)),
                ('cost', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='uploads')),
            ],
        ),
        migrations.CreateModel(
            name='Pocket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pocket_name', models.CharField(max_length=50)),
                ('pocket_type', models.CharField(choices=[('I', 'inside'), ('O', 'Outside')], max_length=1)),
                ('pocket_method', models.CharField(choices=[('Z', 'zipper'), ('B', 'botton'), ('V', 'velcro')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Stamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stamp_name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('cost', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='uploads')),
            ],
            options={
                'ordering': ['stamp_name'],
            },
        ),
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.CreateModel(
            name='Shopper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopper_name', models.CharField(help_text='Enter name', max_length=50)),
                ('material', models.CharField(max_length=50)),
                ('ins_material', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=50)),
                ('cost', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='uploads')),
                ('pocket_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.pocket')),
            ],
        ),
        migrations.CreateModel(
            name='Pouch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pouch_name', models.CharField(max_length=50)),
                ('material', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=50)),
                ('stamp_type', models.CharField(choices=[('Y', 'With print'), ('N', 'Without print')], max_length=1)),
                ('cost', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='uploads')),
                ('stamp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.stamp')),
            ],
        ),
    ]
