# Generated by Django 3.1.2 on 2020-10-17 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20201015_1900'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Other',
        ),
        migrations.RemoveField(
            model_name='pouch',
            name='stamp',
        ),
        migrations.RemoveField(
            model_name='shopper',
            name='pocket_option',
        ),
        migrations.DeleteModel(
            name='Pocket',
        ),
        migrations.DeleteModel(
            name='Pouch',
        ),
        migrations.DeleteModel(
            name='Shopper',
        ),
        migrations.DeleteModel(
            name='Stamp',
        ),
    ]
