# Generated by Django 3.1.2 on 2020-10-17 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20201017_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='author',
            field=models.CharField(default='anonimus', max_length=20, verbose_name='Автор'),
        ),
    ]
