# Generated by Django 3.1.2 on 2020-10-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_articles_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='author',
            field=models.CharField(max_length=20, verbose_name='Автор'),
        ),
    ]
