# Generated by Django 3.1.2 on 2020-10-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20201017_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='date',
            field=models.DateTimeField(default='2020-10-10 00:00:00', verbose_name='Дата публикации'),
        ),
    ]
