# Generated by Django 3.1.2 on 2020-10-21 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20201021_1804'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsrInfo',
        ),
    ]
