# Generated by Django 3.1.2 on 2020-10-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_delete_usrinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='date',
            field=models.DateTimeField(default='2020-10-10 00:00:00', verbose_name='Дата публикации'),
        ),
    ]
