# Generated by Django 3.1.2 on 2020-10-21 15:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_auto_20201021_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 21, 18, 41, 9, 300891), verbose_name='Дата публикации'),
        ),
    ]
