# Generated by Django 3.1.2 on 2020-10-21 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_auto_20201021_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 21, 18, 55, 41, 84411), verbose_name='Дата публикации'),
        ),
    ]
