# Generated by Django 3.1.2 on 2020-10-21 20:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0026_auto_20201021_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 21, 23, 7, 11, 772141), verbose_name='Дата публикации'),
        ),
    ]
