# Generated by Django 3.1.2 on 2020-10-21 20:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0029_auto_20201021_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 21, 23, 21, 42, 390186), verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='login',
            name='about',
            field=models.CharField(max_length=100, verbose_name='ABOUT'),
        ),
    ]
