# Generated by Django 3.1.2 on 2020-10-21 20:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0031_auto_20201021_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='author',
            field=models.CharField(max_length=50, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 21, 23, 26, 4, 405737), verbose_name='Дата публикации'),
        ),
        migrations.DeleteModel(
            name='Login',
        ),
    ]
