# Generated by Django 3.1.2 on 2020-10-21 20:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0034_auto_20201021_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='author_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='articles',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 21, 23, 49, 48, 136325), verbose_name='Дата публикации'),
        ),
    ]
