# Generated by Django 3.1.2 on 2020-10-22 21:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0039_auto_20201021_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 23, 0, 4, 49, 419318), verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
    ]
