# Generated by Django 3.1.2 on 2020-10-22 21:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0040_auto_20201023_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='anons',
            field=models.CharField(max_length=4000, verbose_name='Анонс'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 23, 0, 6, 17, 315820), verbose_name='Дата публикации'),
        ),
    ]
