# Generated by Django 3.0.7 on 2020-10-16 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0010_auto_20200921_1849'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': (('can_post', 'can post'),)},
        ),
    ]
