# Generated by Django 3.1.2 on 2020-10-21 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_articles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Articles',
        ),
    ]
