# Generated by Django 3.0.7 on 2020-09-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_auto_20200918_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='test',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
