# Generated by Django 3.0.7 on 2020-09-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_alter_author_name_20200918_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=15000000000000000000000000000000),
        ),
    ]
