# Generated by Django 3.0.7 on 2020-09-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_auto_20200918_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='test',
            field=models.CharField(default='test', max_length=100),
        ),
    ]
